class CrackLawAIError(Exception):
    """Base exception class for all errors generated by the Legal AI Engine."""
    pass


class LLMProviderError(CrackLawAIError):
    """Raised when an LLM provider API call fails, rate-limits, or times out."""
    pass


class ContextError(CrackLawAIError):
    """Raised when context generation or injection fails (e.g. context budget overflow)."""
    pass


class ValidationError(CrackLawAIError):
    """Raised when a generated response fails critical validation or safety checks."""
    pass


class MemoryError(CrackLawAIError):
    """Raised when an operation on session history or conversation memory fails."""
    pass


class IntentDetectionError(CrackLawAIError):
    """Raised when intent detection fails or returns invalid classes."""
    pass
