import re
import logging
from typing import List, Dict, Any
from src.retrieval.search_result import SearchResultItem

logger = logging.getLogger("CrackLaw.AI.ResponseValidator")

class ResponseValidator:
    """Performs validation checks on LLM responses, ensuring no missing citations, empty content, or broken formatting."""

    def __init__(self):
        pass

    def validate(
        self,
        response_text: str,
        citations: List[Dict[str, Any]],
        retrieved_results: List[SearchResultItem]
    ) -> Dict[str, Any]:
        """Validates response content, structural formatting, and citation indices."""
        errors = []
        warnings = []
        is_valid = True

        # 1. Empty Check
        if not response_text or not response_text.strip():
            errors.append("Empty response generated by LLM.")
            return {
                "is_valid": False,
                "errors": errors,
                "warnings": warnings,
                "status": "FAILED"
            }

        # 2. Broken Formatting Check
        # Check for unclosed markdown code blocks
        if response_text.count("```") % 2 != 0:
            errors.append("Broken formatting: Unclosed markdown code block.")
        
        # Check for unclosed XML tags (such as <document> if LLM accidentally outputs them)
        open_tags = re.findall(r"<([a-zA-Z0-9]+)(?:\s+[^>]*)*>", response_text)
        close_tags = re.findall(r"</([a-zA-Z0-9]+)>", response_text)
        if len(open_tags) != len(close_tags):
            warnings.append("Formatting warning: Mismatched XML tags in response.")

        # 3. Citation Check
        if not citations:
            warnings.append("Missing citations: Response does not reference any retrieved legal source.")

        # 4. Check for invalid index references (e.g. response references [3] when only 2 documents retrieved)
        bracket_indices = []
        for pattern in [re.compile(r"\[Document\s+(\d+)\]", re.IGNORECASE), re.compile(r"\[(\d+)\]")]:
            bracket_indices.extend([int(m) for m in pattern.findall(response_text)])
        
        num_retrieved = len(retrieved_results)
        invalid_refs = [idx for idx in bracket_indices if idx <= 0 or idx > num_retrieved]
        if invalid_refs:
            errors.append(f"Invalid reference indices: Response cited indices {invalid_refs} but only {num_retrieved} documents exist in context.")

        if errors:
            is_valid = False

        status = "PASSED" if is_valid and not errors else "FAILED"
        if not is_valid:
            logger.warning("Response validation failed with errors: %s", errors)
        else:
            logger.info("Response validation passed.")

        return {
            "is_valid": is_valid,
            "errors": errors,
            "warnings": warnings,
            "status": status
        }
